import "server-only";

import {
  DRIVE_API,
  DRIVE_FILE_FIELDS,
  DRIVE_ORDER_BY,
  DRIVE_SCOPE_STRING,
  DRIVE_UPLOAD_API,
  FOLDER_MIME,
  GOOGLE_AUTH_URL,
  GOOGLE_REVOKE_URL,
  GOOGLE_TOKEN_URL,
  GOOGLE_USERINFO_URL,
  DriveHttpError,
  encodeDescription,
  escapeDriveQuery,
  folderByNameQuery,
  folderChildrenQuery,
  mimeTypeFor,
  sanitizeFilename,
  toDriveTrack,
  type DriveTrack,
} from "@/lib/drive";

/**
 * Server-side Google Drive integration.
 *
 * Everything that touches an OAuth token or Drive's network lives here and is
 * imported only from Route Handlers. The client bundle never sees a token, and
 * `server-only` makes that a build-time error rather than a silent leak.
 *
 * Tokens live in an encrypted, httpOnly cookie (see `session.ts`), so a session
 * survives a reload without any server-side database.
 */

/**
 * Called when Drive rejects a token, to obtain a fresh one for a retry.
 *
 * Defined as a named type because it appears in eight signatures, and because
 * getting it wrong (assuming a sync return) silently type-checks fine while
 * sending the literal string "[object Promise]" as a bearer token.
 */
export type RetryFn = () => Promise<string>;

/* -- configuration -- */

/** OAuth client credentials, read from the environment. */
export interface DriveConfig {
  clientId: string;
  clientSecret: string;
  /** Absolute URL Google redirects back to after consent. */
  redirectUri: string;
}

function env(name: string): string {
  const v = process.env[name];
  return typeof v === "string" ? v.trim() : "";
}

/**
 * Read the OAuth configuration, or null when Drive is not set up.
 *
 * A missing client id is a normal state, not an exception: the app must still
 * boot and play its generative tracks on a machine with no Drive credentials.
 */
export function readConfig(): DriveConfig | null {
  const clientId = env("GOOGLE_CLIENT_ID");
  const clientSecret = env("GOOGLE_CLIENT_SECRET");
  const redirectUri = env("GOOGLE_REDIRECT_URI");
  if (!clientId || !clientSecret || !redirectUri) return null;
  return { clientId, clientSecret, redirectUri };
}

/** True when the server has everything it needs to talk to Drive. */
export function isConfigured(): boolean {
  return readConfig() !== null;
}

/* -- OAuth -- */

/**
 * The URL that starts the consent flow.
 *
 * `access_type=offline` + `prompt=consent` are what make Google issue a refresh
 * token, without which the connection would silently expire after an hour.
 *
 * `state` is a CSRF nonce generated by the caller and verified on the way back.
 */
export function authorizationUrl(config: DriveConfig, state: string): string {
  const params = new URLSearchParams({
    client_id: config.clientId,
    redirect_uri: config.redirectUri,
    response_type: "code",
    scope: DRIVE_SCOPE_STRING,
    access_type: "offline",
    prompt: "consent",
    include_granted_scopes: "true",
    state,
  });
  return `${GOOGLE_AUTH_URL}?${params.toString()}`;
}

interface TokenResponse {
  access_token?: string;
  refresh_token?: string;
  expires_in?: number;
  scope?: string;
  token_type?: string;
  error?: string;
  error_description?: string;
}

async function postToken(body: URLSearchParams): Promise<TokenResponse> {
  const res = await fetch(GOOGLE_TOKEN_URL, {
    method: "POST",
    headers: { "Content-Type": "application/x-www-form-urlencoded" },
    body,
    cache: "no-store",
  });
  const json = (await res.json().catch(() => ({}))) as TokenResponse;
  if (!res.ok) {
    // Google returns 400 with a JSON error for a bad code or revoked grant.
    throw new DriveHttpError(
      res.status,
      json.error_description || json.error || "Google rejected the token request.",
    );
  }
  return json;
}

/** Exchange an authorization code for tokens. */
export async function exchangeCode(
  config: DriveConfig,
  code: string,
): Promise<TokenResponse> {
  return postToken(
    new URLSearchParams({
      code,
      client_id: config.clientId,
      client_secret: config.clientSecret,
      redirect_uri: config.redirectUri,
      grant_type: "authorization_code",
    }),
  );
}

/** A short-lived access token plus a refresh token. */
export interface SessionTokens {
  accessToken: string;
  refreshToken: string;
  /** Absolute expiry in epoch ms, so a cookie round-trip keeps it meaningful. */
  expiresAt: number;
}

/** Turn a token response into stored session tokens, defaulting the expiry. */
export function toSessionTokens(json: TokenResponse): SessionTokens {
  if (!json.access_token) {
    throw new DriveHttpError(400, "Google did not return an access token.");
  }
  const expiresIn = Number(json.expires_in);
  return {
    accessToken: json.access_token,
    refreshToken: json.refresh_token ?? "",
    expiresAt: Date.now() + (Number.isFinite(expiresIn) ? expiresIn : 3600) * 1000,
  };
}

/**
 * Trade a refresh token for a fresh access token.
 *
 * Google omits `refresh_token` from refresh responses, so the caller must keep
 * the one it already has.
 */
export async function refreshTokens(
  config: DriveConfig,
  refreshToken: string,
): Promise<SessionTokens> {
  const json = await postToken(
    new URLSearchParams({
      refresh_token: refreshToken,
      client_id: config.clientId,
      client_secret: config.clientSecret,
      grant_type: "refresh_token",
    }),
  );
  return { ...toSessionTokens(json), refreshToken };
}

/** Revoke a token so the grant dies immediately rather than at expiry. */
export async function revoke(token: string): Promise<void> {
  try {
    await fetch(GOOGLE_REVOKE_URL, {
      method: "POST",
      headers: { "Content-Type": "application/x-www-form-urlencoded" },
      body: new URLSearchParams({ token }),
      cache: "no-store",
    });
  } catch {
    /* revoking is best-effort: the cookie is cleared either way */
  }
}

/** The connected account, for showing "Signed in as …" in the UI. */
export async function fetchAccount(
  accessToken: string,
): Promise<{ email: string; name?: string }> {
  const res = await driveFetch(
    `${GOOGLE_USERINFO_URL}?fields=${encodeURIComponent("email,name")}`,
    accessToken,
  );
  const json = (await res.json().catch(() => ({}))) as {
    email?: string;
    name?: string;
  };
  return { email: json.email ?? "", name: json.name };
}

/* -- Drive transport -- */

/** Perform an authenticated Drive request, with a retry on a stale token. */
async function driveFetch(
  url: string,
  accessToken: string,
  init: RequestInit = {},
  onRetry?: RetryFn,
): Promise<Response> {
  const headers = new Headers(init.headers);
  headers.set("Authorization", `Bearer ${accessToken}`);
  const res = await fetch(url, { ...init, headers, cache: "no-store" });

  // 401 means the access token expired mid-flight; refresh once and retry.
  if (res.status === 401 && onRetry) {
    const fresh = await onRetry();
    return driveFetch(url, fresh, init);
  }
  if (!res.ok) {
    const detail = await res.text().catch(() => "");
    throw new DriveHttpError(res.status, googleError(detail, res.status));
  }
  return res;
}

/** Pull the useful sentence out of Google's JSON error body. */
function googleError(body: string, status: number): string {
  try {
    const parsed = JSON.parse(body) as {
      error?: { message?: string } | string;
    };
    const message = typeof parsed.error === "string" ? parsed.error : parsed.error?.message;
    if (message) return message;
  } catch {
    /* not JSON — fall through to the status-based default */
  }
  return `Google Drive returned ${status}.`;
}

/* -- folders -- */

/**
 * Find AETHER's folder in My Drive, creating it on first use.
 *
 * Cached per access-token fingerprint for the process lifetime so every list
 * and upload doesn't re-issue a search; a folder id is stable for the life of
 * the file, so this is safe to cache.
 */
const folderCache = new Map<string, string>();

/** Resolve (and memoise) the id of AETHER's music folder. */
export async function ensureFolder(
  accessToken: string,
  name: string,
  onRetry?: RetryFn,
): Promise<string> {
  const cacheKey = `${accessToken.slice(-12)}:${name}`;
  const hit = folderCache.get(cacheKey);
  if (hit) return hit;

  const search = await driveFetch(
    `${DRIVE_API}/files?q=${encodeURIComponent(folderByNameQuery(name))}` +
      `&fields=${encodeURIComponent("files(id,name)")}&spaces=drive`,
    accessToken,
    {},
    onRetry,
  );
  const found = (await search.json().catch(() => ({}))) as { files?: { id: string }[] };
  const existing = found.files?.[0]?.id;
  if (existing) {
    folderCache.set(cacheKey, existing);
    return existing;
  }

  const created = await driveFetch(
    `${DRIVE_API}/files`,
    accessToken,
    {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        name,
        mimeType: FOLDER_MIME,
        parents: ["root"],
      }),
    },
    onRetry,
  );
  const folder = (await created.json().catch(() => ({}))) as { id?: string };
  if (!folder.id) throw new DriveHttpError(500, "Could not create the Drive folder.");
  folderCache.set(cacheKey, folder.id);
  return folder.id;
}

/* -- files -- */

/** List every track in AETHER's folder, newest first, following pagination. */
export async function listTracks(
  accessToken: string,
  folderName: string,
  onRetry?: RetryFn,
): Promise<DriveTrack[]> {
  const folderId = await ensureFolder(accessToken, folderName, onRetry);
  const tracks: DriveTrack[] = [];
  let pageToken: string | undefined;

  // Drive caps a page at 1000 items; a large library needs several pages.
  do {
    const params = new URLSearchParams({
      q: folderChildrenQuery(folderId),
      fields: DRIVE_FILE_FIELDS,
      orderBy: DRIVE_ORDER_BY,
      pageSize: "200",
      spaces: "drive",
      // Skip Google Docs-style folders; we only ever list audio we uploaded.
      includeItemsFromAllDrives: "true",
      supportsAllDrives: "true",
    });
    if (pageToken) params.set("pageToken", pageToken);

    const res = await driveFetch(
      `${DRIVE_API}/files?${params.toString()}`,
      accessToken,
      {},
      onRetry,
    );
    const page = (await res.json().catch(() => ({}))) as {
      files?: Parameters<typeof toDriveTrack>[0][];
      nextPageToken?: string;
    };
    for (const file of page.files ?? []) {
      // Only surface things that can actually be played back.
      if (file.mimeType === FOLDER_MIME) continue;
      const track = toDriveTrack(file);
      if (track.fileId && track.mimeType.startsWith("audio/")) tracks.push(track);
    }
    pageToken = page.nextPageToken || undefined;
  } while (pageToken);

  return tracks;
}

/** Fetch one file's metadata, or null when it no longer exists. */
export async function getTrack(
  accessToken: string,
  fileId: string,
  onRetry?: RetryFn,
): Promise<DriveTrack | null> {
  const params = new URLSearchParams({
    fields: "id,name,mimeType,size,description,createdTime,modifiedTime,thumbnailLink",
    supportsAllDrives: "true",
  });
  const res = await fetch(`${DRIVE_API}/files/${encodeURIComponent(fileId)}?${params}`, {
    headers: { Authorization: `Bearer ${accessToken}` },
    cache: "no-store",
  });
  if (res.status === 404) return null;
  if (res.status === 401 && onRetry) return getTrack(await onRetry(), fileId);
  if (!res.ok) {
    throw new DriveHttpError(res.status, googleError(await res.text().catch(() => ""), res.status));
  }
  return toDriveTrack((await res.json()) as Parameters<typeof toDriveTrack>[0]);
}

/** The metadata written alongside an upload. */
interface FileMetadata {
  name: string;
  parents: string[];
  mimeType: string;
  description: string;
}

/**
 * Start a resumable upload and return the session URL the browser PUTs to.
 *
 * Resumable is used even for small files because it lets the bytes travel
 * directly from the browser to Google: a large album never has to fit in this
 * server's memory, and a flaky connection can be retried from the start without
 * re-sending everything.
 */
export async function createUploadSession(
  accessToken: string,
  file: { name: string; bytes: number; mimeType: string; title?: string; artist?: string },
  folderName: string,
  onRetry?: RetryFn,
): Promise<{ uploadUrl: string; fileId: string }> {
  const folderId = await ensureFolder(accessToken, folderName, onRetry);
  const name = sanitizeFilename(file.name || "Untitled");
  const mimeType = file.mimeType || mimeTypeFor(name) || "audio/mpeg";
  const metadata: FileMetadata = {
    name,
    parents: [folderId],
    mimeType,
    description: encodeDescription({ title: file.title, artist: file.artist }),
  };

  const res = await fetch(
    `${DRIVE_UPLOAD_API}/files?uploadType=resumable&supportsAllDrives=true&` +
      `fields=${encodeURIComponent("id,name,size,mimeType,description,createdTime,modifiedTime")}`,
    {
      method: "POST",
      headers: {
        Authorization: `Bearer ${accessToken}`,
        "Content-Type": "application/json; charset=UTF-8",
        "X-Upload-Content-Type": mimeType,
        // Google uses this to pre-allocate; it must match what we PUT.
        "X-Upload-Content-Length": String(Math.max(0, Math.floor(file.bytes))),
      },
      body: JSON.stringify(metadata),
      cache: "no-store",
    },
  );

  if (res.status === 401 && onRetry) {
    return createUploadSession(await onRetry(), file, folderName);
  }
  if (!res.ok) {
    throw new DriveHttpError(
      res.status,
      googleError(await res.text().catch(() => ""), res.status),
    );
  }

  const uploadUrl = res.headers.get("Location");
  if (!uploadUrl) {
    throw new DriveHttpError(502, "Google did not return an upload session.");
  }
  // The session URL embeds the access token, so it must never be logged.
  const created = (await res.json().catch(() => ({}))) as { id?: string };
  return { uploadUrl, fileId: created.id ?? "" };
}

/**
 * Update a track's description, which is where AETHER keeps its metadata.
 *
 * Reading the current value first matters: Drive replaces the whole field, so
 * patching `description` with only a duration would silently erase the title.
 */
export async function updateMetadata(
  accessToken: string,
  fileId: string,
  patch: { title?: string; artist?: string; duration?: number },
  onRetry?: RetryFn,
): Promise<void> {
  const current = await getTrack(accessToken, fileId, onRetry);
  if (!current) throw new DriveHttpError(404, "That file is no longer in Drive.");

  const description = encodeDescription({
    title: patch.title?.trim() || current.title,
    artist: patch.artist?.trim() || current.artist,
    duration: patch.duration ?? current.duration,
  });

  const res = await fetch(
    `${DRIVE_API}/files/${encodeURIComponent(fileId)}?supportsAllDrives=true&fields=id`,
    {
      method: "PATCH",
      headers: {
        Authorization: `Bearer ${accessToken}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({ description }),
      cache: "no-store",
    },
  );
  if (res.status === 401 && onRetry) {
    return updateMetadata(await onRetry(), fileId, patch);
  }
  if (!res.ok) {
    throw new DriveHttpError(
      res.status,
      googleError(await res.text().catch(() => ""), res.status),
    );
  }
}

/** Delete a file. Permanent, so callers must mean it. */
export async function deleteTrack(
  accessToken: string,
  fileId: string,
  onRetry?: RetryFn,
): Promise<void> {
  const res = await fetch(
    `${DRIVE_API}/files/${encodeURIComponent(fileId)}?supportsAllDrives=true`,
    { method: "DELETE", headers: { Authorization: `Bearer ${accessToken}` }, cache: "no-store" },
  );
  if (res.status === 401 && onRetry) {
    return deleteTrack(await onRetry(), fileId);
  }
  if (!res.ok && res.status !== 404) {
    throw new DriveHttpError(
      res.status,
      googleError(await res.text().catch(() => ""), res.status),
    );
  }
}

/* -- media -- */

/** Headers worth forwarding from a Drive media response to the browser. */
const MEDIA_HEADERS = ["content-type", "content-length", "content-range", "accept-ranges"];

/**
 * Stream a file's bytes, forwarding the client's Range header.
 *
 * Range is the whole point: without it the browser cannot seek, and the
 * `HTMLAudioElement` in the engine would be stuck at linear playback. Drive
 * honours `Range` on media downloads and answers 206, so the status and
 * `content-range` are passed straight through rather than reconstructed.
 */
export async function streamMedia(
  accessToken: string,
  fileId: string,
  range: string | null,
  onRetry?: RetryFn,
): Promise<Response> {
  const params = new URLSearchParams({ alt: "media", supportsAllDrives: "true" });
  const headers: Record<string, string> = {
    Authorization: `Bearer ${accessToken}`,
  };
  // Only forward a syntactically valid single byte range; anything else
  // (multi-range, a suffix range with no length) is dropped so Drive answers
  // with the full body rather than something the element cannot use.
  if (range && /^bytes=\d*-\d*$/.test(range.trim())) headers.Range = range.trim();

  const res = await fetch(`${DRIVE_API}/files/${encodeURIComponent(fileId)}?${params}`, {
    headers,
    cache: "no-store",
  });

  if (res.status === 401 && onRetry) {
    return streamMedia(await onRetry(), fileId, range);
  }
  if (!res.ok && res.status !== 206) {
    throw new DriveHttpError(
      res.status,
      googleError(await res.text().catch(() => ""), res.status),
    );
  }

  const out = new Headers();
  for (const name of MEDIA_HEADERS) {
    const value = res.headers.get(name);
    if (value) out.set(name, value);
  }
  // Audio is range-capable and must never be cached: it is private, and a
  // stale entry would keep playing after the user disconnects.
  out.set("accept-ranges", "bytes");
  out.set("cache-control", "private, no-store");

  // 206 must keep its status, or the element treats the range as the whole file.
  return new Response(res.body, { status: res.status, headers: out });
}

/** Escape helper re-exported for the route handlers' folder-name env var. */
export { escapeDriveQuery };
